import "std";

func print_elements(iter: std::iterator[[u32]]) void {
    for iter.advance() {
        std::print_format_line(
            std::out(),
            "{}",
            (:[]std::formatter)[
                std::formatter::init[[u32]](iter.current())]);
    }
}

func main() void {
    var iter = std::slice_iterator[[u32]]::init((:[]u32)[]);
    print_elements(std::iterator[[u32]]::init[[std::slice_iterator[[u32]]]](&iter));

    var iter = std::slice_iterator[[u32]]::init((:[]u32)[1, 2, 3]);
    print_elements(std::iterator[[u32]]::init[[std::slice_iterator[[u32]]]](&iter));

    assert not iter.advance();
    assert not iter.advance(); # Should be able to advance multiple times without panic.
    iter.current(); # Iterator was used up. This should panic.
}
################################################################################
# 1
# 2
# 3
# panic: invalid iterator
