import "std";
import "sys";

func main() void {
    var a: std::result[[void, u16]] = std::result[[void, u16]]::init_error(0xBEEF);
    assert not a.is_value();
    assert a.is_error();
    sys::dump[[u16]](a.error());
    a.value(); # boom
}
################################################################################
# EF BE
# panic: attempted to retrieve value from std::result in the error state
